"""Add transporteur_id and vehicule_id to Prestation

Revision ID: 1d303b78b865
Revises: 
Create Date: 2025-04-06 09:04:30.870388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d303b78b865'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_client')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('code_postal',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('ville',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('pays',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True,
               existing_server_default=sa.text("'France'"))
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('prestation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transporteur_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vehicule_id', sa.Integer(), nullable=True))
        batch_op.alter_column('date_modification',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('idx_prestation_archive')
        batch_op.drop_index('idx_prestation_client')
        batch_op.drop_index('idx_prestation_dates')
        batch_op.drop_index('idx_prestation_statut')
        batch_op.drop_index('idx_prestation_tags')
        batch_op.drop_index('idx_prestation_type_demenagement')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'transporteurs', ['transporteur_id'], ['id'])
        batch_op.create_foreign_key(None, 'vehicules', ['vehicule_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['modifie_par'], ['id'])
        batch_op.drop_column('derniere_modification_par')
        batch_op.drop_column('date_derniere_modification')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_type_vehicule')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_user_type_vehicule', ['type_vehicule_id'], unique=False)

    with op.batch_alter_table('prestation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_derniere_modification', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('derniere_modification_par', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['derniere_modification_par'], ['id'])
        batch_op.create_index('idx_prestation_type_demenagement', ['type_demenagement_id'], unique=False)
        batch_op.create_index('idx_prestation_tags', ['tags'], unique=False)
        batch_op.create_index('idx_prestation_statut', ['statut'], unique=False)
        batch_op.create_index('idx_prestation_dates', ['date_debut', 'date_fin'], unique=False)
        batch_op.create_index('idx_prestation_client', ['client_id'], unique=False)
        batch_op.create_index('idx_prestation_archive', ['archive'], unique=False)
        batch_op.alter_column('date_modification',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.drop_column('vehicule_id')
        batch_op.drop_column('transporteur_id')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('pays',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'France'"))
        batch_op.alter_column('ville',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('code_postal',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('_alembic_tmp_client',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nom', sa.VARCHAR(length=64), nullable=False),
    sa.Column('prenom', sa.VARCHAR(length=64), nullable=False),
    sa.Column('adresse', sa.TEXT(), nullable=True),
    sa.Column('telephone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('type_client', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tags', sa.TEXT(), nullable=True),
    sa.Column('archive', sa.BOOLEAN(), nullable=True),
    sa.Column('date_creation', sa.DATETIME(), nullable=False),
    sa.Column('code_postal', sa.VARCHAR(length=10), nullable=True),
    sa.Column('ville', sa.VARCHAR(length=64), nullable=True),
    sa.Column('pays', sa.VARCHAR(length=64), server_default=sa.text("'France'"), nullable=True),
    sa.Column('statut', sa.VARCHAR(length=20), server_default=sa.text("'actif'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
